<?php

namespace AppBundle\Repository;

/**
 * ShortUrlRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShortUrlRepository extends \Doctrine\ORM\EntityRepository
{
    // Returns the last 5 generated urls
	public function findLastFiveShortUrls()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT s FROM AppBundle:ShortUrl s ORDER BY s.createdAt DESC '
            )
            ->setMaxResults(5)
            ->getResult();
    }
}
